# Using mise to manage goclaw

redactions = [ "*_API_KEY*", "*_TOKEN", "_PASSWORD" ]

[settings]
env_shell_expand = true

[env]
_.file = { path = ".env" }
_.source = { path = "mise/scripts/compose_file.sh" , tools = true }

GOCLAW_GATEWAY_TOKEN={ required = "Create using ./prepare-env.sh" }
GOCLAW_ENCRYPTION_KEY={ required = "Create using ./prepare-env.sh" }

# API key mappings

GOCLAW_OPENROUTER_API_KEY = "${OPENROUTER_API_KEY:-}"
GOCLAW_GEMINI_API_KEY = "${GEMINI_API_KEY:-}"
GOCLAW_MINIMAX_API_KEY = "${MINIMAX_API_KEY:-}"


# Ironically docker compose is not composable (http://github.com/keithy/sprankle-pod)
# postgres:gateway:selfservice:sandbox:browser:otel:tailscale:upgrade:vnstock-mcp
GOCLAW_MODULES = 'postgres:selfservice'

PROJECT_UPSTREAM_URL = "https://github.com/nextlevelbuilder/goclaw"
PROJECT_ORIGIN_URL = "${PROJECT_UPSTREAM_URL}"

# Localise further in goclaw/mise.local.toml
