# Using mise to manage goclaw

redactions = [ "*_API_KEY*", "*_TOKEN", "_PASSWORD" ]

[settings]
env_shell_expand = true

[shell_alias]
docker = "podman"

[env]
_.file = { path = ".env" }
_.source = { path = "mise/compose_file.sh" , tools = true }
GOCLAW_GATEWAY_TOKEN={ required = "Create using ./prepare-env.sh" }
GOCLAW_ENCRYPTION_KEY={ required = "Create using ./prepare-env.sh" }

# Our API key mappings

GOCLAW_OPENROUTER_API_KEY = "${OPENROUTER_API_KEY:-}"
GOCLAW_GEMINI_API_KEY = "${GEMINI_API_KEY_angels:-}"
GOCLAW_MINIMAX_API_KEY = "${MINIMAX_API_KEY:-}"


# Ironically docker compose is not composable (http://github.com/keithy/sprankle-pod)
# postgres:gateway:selfservice:sandbox:browser:otel:tailscale:upgrade:vnstock-mcp

GOCLAW_MODULES = 'postgres:selfservice'

# --- Database (only for non-Docker deployments) ---
# Docker Compose auto-builds this from POSTGRES_USER/PASSWORD/DB.
# GOCLAW_POSTGRES_DSN=postgres://user:pass@host:5432/dbname?sslmode=disable

# --- Debug ---
GOCLAW_TRACE_VERBOSE=1
CONTAINERS_REGISTRIES_CONF="{{config_root}}/mise/registries.conf"
# CONTAINERS_STORAGE_CONF="{{config_root}}/mise/storage.conf"
